const PROD_BRANCH_NAME = process.env.PROD_BRANCH_NAME || 'master';

const DEPLOY_SERVER =
  process.env.CIRCLE_BRANCH === PROD_BRANCH_NAME ? 'PROD' : 'PREVIEW';

// Pull from different env vars based on branch
module.exports = {
  CIRCLE_REPO_URL: process.env.CIRCLE_REPOSITORY_URL,
  CONTENT_BUNDLE_RELEASES_AUTH_TOKEN:
    process.env[`${DEPLOY_SERVER}_CONTENT_BUNDLE_RELEASES_AUTH_TOKEN`],
  CONTENT_BUNDLES_URL: process.env[`${DEPLOY_SERVER}_CONTENT_BUNDLES_URL`],
  PROGRAM_STRUCTURES_AUTH_TOKEN:
    process.env[`${DEPLOY_SERVER}_PROGRAM_STRUCTURES_AUTH_TOKEN`],
  PROGRAM_STRUCTURES_URL:
    process.env[`${DEPLOY_SERVER}_PROGRAM_STRUCTURES_URL`],
  S3_ACCESS_KEY: process.env[`S3_${DEPLOY_SERVER}_ACCESS_KEY`],
  S3_BUCKET: process.env[`S3_${DEPLOY_SERVER}_BUCKET`],
  S3_SECRET_KEY: process.env[`S3_${DEPLOY_SERVER}_SECRET_KEY`],
};
